WeatherForecast/Models/HistoryUserRequest.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeatherForecast.Models
{
    [Table("CityLog")]
    public class CityLog
    {
        public int Id { get; set; }
        [Required]
        public string CityName { get; set; }
        public DateTime RequestTime { get; set; }
    }
}

WeatherForecast/Models/SavedCity.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeatherForecast.Models
{
    [Table("Cities")]
    public class SavedCity
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string CityName { get; set; }
    }
}

WeatherForecast/Models/WeatherJson.cs
using System.Collections.Generic;

namespace WeatherForecast.Models
{
    public class Coord
    {
        public double lon { get; set; }
        public double lat { get; set; }
    }

    public class City
    {
        public int id { get; set; }
        public string name { get; set; }
        public Coord coord { get; set; }
        public string country { get; set; }
        public int population { get; set; }
    }

    public class Temp
    {
        public double day { get; set; }
        public double min { get; set; }
        public double max { get; set; }
        public double night { get; set; }
        public double eve { get; set; }
        public double morn { get; set; }
    }

    public class Weather
    {
        public int id { get; set; }
        public string main { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
    }

    public class List
    {
        public int dt { get; set; }
        public Temp temp { get; set; }
        public double pressure { get; set; }
        public int humidity { get; set; }
        public List<Weather> weather { get; set; }
        public double speed { get; set; }
        public int deg { get; set; }
        public int clouds { get; set; }
        public double rain { get; set; }
    }

    public class RootObject
    {
        public City city { get; set; }
        public string cod { get; set; }
        public double message { get; set; }
        public int cnt { get; set; }
        public List<List> list { get; set; }
    }
}

WeatherForecast/Controllers/ConfigureCitiesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using WeatherForecast.Context;
using WeatherForecast.Models;

namespace WeatherForecast.Controllers
{
    public class ConfigureCitiesController : Controller
    {
        IRepository<SavedCity> _savedCity;

        public ConfigureCitiesController(IRepository<SavedCity> savedCity)
        {
            _savedCity = savedCity;
        }


        // GET:  ConfigureCities/Configure
        [HttpGet]
        public ActionResult Configure()
        {
            IEnumerable<SavedCity> cities = _savedCity.Get();
            return View(cities);
        }

        public ActionResult Delete(int? id)
        {
            _savedCity.DeleteAsync(id.Value);
            return RedirectToAction("Configure");
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCityAsynk(int id, string cityName)
        {
            var cityUpdate = await _savedCity.GetByIdAsync(id);
            cityUpdate.CityName = cityName;
            _savedCity.Save();
            return Json(new { Udpated = true });
        }

        public ActionResult AddCity()
        {
            return View("AddCity");
        }

        [HttpPost]
        public ActionResult AddCity(string cityName)
        {
            SavedCity newCity = new SavedCity() { CityName = cityName };
            _savedCity.Add(newCity);
            _savedCity.Save();
            return RedirectToAction("Configure");
        }

    }
}

WeatherForecast/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Ninject;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeatherForecast.Services;
using WeatherForecast.Models;
using System.Net;
using WeatherForecast.Context;
using System.Threading.Tasks;

namespace WeatherForecast.Controllers
{
    public class HomeController : Controller
    {
        ICityLogRepository _cityLog;
        IWeatherForecastProvider _weather;
        IRepository<SavedCity> _savedCity;

        public HomeController(IWeatherForecastProvider weather,
                              IRepository<SavedCity> savedCity,
                              ICityLogRepository cityLog)
        {
            _weather = weather;
            _savedCity = savedCity;
            _cityLog = cityLog;
        }

        public ActionResult Index()
        {
            IEnumerable<SavedCity> cities = _savedCity.Get();
            return View(cities);
        }

        // GET: Home/GetForecast
        [HttpGet]
        public async Task<ActionResult> GetForecast(string cityoflist, string cityOwn, string daysnumb)
        {
            string city = cityOwn != "" ? cityOwn : cityoflist;
            var model = await _weather.GetWeatherForecastJsonAsync(cityoflist, Convert.ToInt32(daysnumb), cityOwn);
            _cityLog.AddLog(new CityLog
            {
                CityName = city,
                RequestTime = DateTime.Now
            });
            _cityLog.Save();
            return model == null ? View("Error") : View("GetForecast", model);
        }

        // GET: Home/CityLog
        [HttpGet]
        public ActionResult CityLog()
        {
            return View("CityLog",_cityLog.GetCitiesLog());
        }

        public ActionResult ClearHistory()
        {
            _cityLog.DeleteAll();
            return View("CityLog");
        }
        

    }
}

WeatherForecast/Views/ConfigureCities/AddCity.cshtml
@model IEnumerable<WeatherForecast.Models.SavedCity>
@{

    ViewBag.Title = "Adding new City";
}
<div class="row">
    @using (Html.BeginForm("AddCity", "ConfigureCities", FormMethod.Post))
    {
        <div class="form-group" style="margin-top: 30px">
            <label for="newCity">Please add your city</label>
            @Html.TextBox("cityName", null, new { @class = "form-control" })
        </div>
        <input type="submit" class="btn btn-default" value="Add new city" />
    }
</div>

WeatherForecast/Views/ConfigureCities/Configure.cshtml
@model IEnumerable<WeatherForecast.Models.SavedCity>
@{

    ViewBag.Title = "Configuration of city list";
}


<div class="forecast_wrapper">
        <table>
            @foreach (var city in Model)
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(modelItem => city.CityName, new { @class = "form-control", id = $"cityEdit_{city.Id}" })
                    </td>
                    <td align="right">
                        <a href="#" onclick="updateCity(@city.Id)"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></a>
                        <a href="~/ConfigureCities/Delete/@city.Id"><i> Delete</i></a>
                    </td>
                </tr>
            }                    
        </table>
    </div>
<p class="forecast_wrapper">@Html.ActionLink("Add new City", "AddCity")</p>
@section scripts{
    <script src="~/Scripts/city.js"></script>
}

WeatherForecast/Views/Home/CityLog.cshtml
@model IEnumerable<WeatherForecast.Models.CityLog>
<div class="container">
    <div class="col-md-8" style="margin-top:50px">
        @if (Model != null)
        {
            <table class="table table-hover table-condensed" style="width:80%">
                <thead>
                    <tr>
                        <th>City</th>
                        <th>Search Time</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CityName</td>
                        <td>@item.RequestTime</td>
                    </tr>
                }
            </table>
        }else
        {
            <h2>There is no history yet</h2>
        }
        <div>
            @Html.ActionLink("Clear search history", "ClearHistory")
        </div>
    </div>
</div>

WeatherForecast/Views/Home/GetForecast.cshtml
@model WeatherForecast.Models.RootObject
@{
    ViewBag.Title = "GetForecast";
}

<body>
    <div id="forecast_city">
        <h2>@Model.city.name</h2>
        <p>The weather in @Model.city.name @Model.city.country</p>
    </div>
    @foreach (var weatherDay in Model.list)
    {
        var date = new DateTime(1970, 1, 1, 0, 0, 0, 0).ToLocalTime().AddSeconds(weatherDay.dt).ToShortDateString();
        var icon = $"http://openweathermap.org/img/w/{weatherDay.weather.Select(w => w.icon).FirstOrDefault()}.png";
        <div class="forecast_wrapper">
            <h3>Date: @date <img src="@icon"></h3>
            <ul>
                <li>Day temperature:     @weatherDay.temp.day </li>
                <li>Morning temperature: @weatherDay.temp.morn</li>
                <li>Night temperature:   @weatherDay.temp.night</li>
                <li>Humidity:            @weatherDay.humidity</li>
                <li id="wind">Wind Speed:@weatherDay.speed</li>
            </ul>
        </div>
    }
</body>

WeatherForecast/Views/Home/Index.cshtml
@model IEnumerable<WeatherForecast.Models.SavedCity>
@{
    ViewBag.Title = "Home Page";
    var daysnumbSelect = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "weather for 1 day",
                    Value = "1",
                    Selected = true
                },
                new SelectListItem
                {
                    Text = "weather for 3 days",
                    Value = "3"
                },
                new SelectListItem
                {
                    Text = "weather for 7 days",
                    Value = "7",
                },
            };

    var cityoflist = new List<SelectListItem>();
    foreach (var city in Model)
    {
        var cityValue = new SelectListItem
        {
            Text = city.CityName,
            Value = city.CityName
        };
        cityoflist.Add(cityValue);
    }
}

<div class="forecast_wrapper">
    @using (Html.BeginForm("GetForecast", "Home", FormMethod.Get))
    {
        <div class="form-group" style="margin-top: 30px">
            <label for="cityoflist">Choose city from list or enter your own:</label>
            @Html.DropDownList("cityoflist", cityoflist, new { @class = "form-control" })
            <label for="cityOwn">Enter city:</label>
            @Html.TextBox("cityOwn", null, new { @class = "form-control" })
            <label for="daysnumb">Select numer of days you wanna forecast:</label>
            @Html.DropDownList("daysnumb", daysnumbSelect, new { @class = "form-control" })
        </div>
        <input type="submit" class="btn btn-default" value="Get forecast"  style="width:100%"/>
    }
</div>

WeatherForecast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <title>@ViewBag.Title Weather Forecast</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Site.css" />

</head>
<body>
    <header class="menu-flex-container">
        <div class="menu-flex-item">
            <a href="/Home" id="logo">
                <img src="~/Content/Images/weather.png" alt="Weather icon" />
                Weather App
            </a>
        </div>
        <div class="menu-flex-items-container">
            <ul>
                <li>@Html.ActionLink("Weather", "Index", "Home")</li>
                <li>@Html.ActionLink("Configure Cities", "Configure", "ConfigureCities")</li>
                <li>@Html.ActionLink("City search history", "CityLog", "Home")</li>
            </ul>
        </div>
    </header>

    <div class="container body-content">
        @RenderBody()
    </div>
        <footer class="footer-flex-container">
            <div id="footer-info">
                <p>Weather forecast company </p>
                <p>With this U can always find actual weather forescat</p>
                <p>&copy; @DateTime.Now.Year –  All Rights Reserved.</p>
            </div>
            <div id="footer-contact">
                <p>03058, Ukraine</p>
                <p>Kiev, prosp. Kosmonavta Komarova 1</p>
                <p>(044)406-79-01</p>
            </div>
        </footer>   

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>